#!/bin/bash
source /etc/environment

influxdb_proxy=$(/usr/bin/etcdctl get /influxdb/proxy)

/usr/bin/docker run --rm -p 80:80 \
  -e HTTP_USER=admin \
  -e HTTP_PASS=admin \
  -e INFLUXDB_HOST="${influxdb_proxy}" \
  -e INFLUXDB_PORT=8086 \
  -e INFLUXDB_NAME=server_metrics \
  -e INFLUXDB_USER=root \
  -e INFLUXDB_PASS=root \
  -e INFLUXDB_IS_GRAFANADB=true \
  tutum/grafana
