#!/bin/bash
source /etc/environment

curl -L http://127.0.0.1:4001/v2/keys/influxdb/master?prevExist=false -XPUT -d value=${PRIVATE_IPV4}
master=$(/usr/bin/etcdctl get /influxdb/master -consistent)

if [ "$master" != "$PRIVATE_IPV4" ];
then
  seed="-e SEED=${master}:8090"
fi

/usr/bin/docker run --rm \
--name $1 \
-v /data/influxdb/:/data/influxdb/ \
-p 8083:8083 -p 8086:8086 -p 8090:8090 -p 8099:8099 \
-e SERVICE_NAME=$1 \
-e HOSTNAME="${PRIVATE_IPV4}" \
${seed} allen13/influxdb-min
